name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Download JDK with JavaFX
      run: wget -O jdk8.tar.gz https://static.azul.com/zulu/bin/zulu8.33.0.1-ca-fx-jdk8.0.192-linux_x64.tar.gz

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        jdkFile: jdk8.tar.gz

    - name: Build with Gradle
      run: ./gradlew build

    - name: Deploy
      run: ./gradlew publish
      if: github.event_name == 'push' && github.ref == 'refs/heads/revival'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}'
